CREATE DATABASE QL_SX
USE QL_SX
CREATE TABLE LOAI
(
	MALOAI CHAR(5) PRIMARY KEY,
	TENLOAI NVARCHAR(50)
)

CREATE TABLE SANPHAM
(
	MASP CHAR(5) PRIMARY KEY,
	TENSP NVARCHAR(50),
	MALOAI CHAR(5) FOREIGN KEY(MALOAI) REFERENCES SANPHAM,
	CONSTRAINT TENSP_DUYNHAT UNIQUE(TENSP)
)

set dateformat dmy
CREATE TABLE NHANVIEN
(
	MANV CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	CHECK(DATEDIFF(YEAR, NGAYSINH, GETDATE()) >= 18 AND DATEDIFF(YEAR, NGAYSINH, GETDATE()) <= 55),
	PHAI BIT NOT NULL DEFAULT 0
)

set dateformat dmy
CREATE TABLE PHIEUXUAT
(
	MAPX INT IDENTITY(1,1) PRIMARY KEY,
	NGAYLAP DATE,
	MANV CHAR(5) FOREIGN KEY(MANV) REFERENCES NHANVIEN
)
DROP TABLE PHIEUXUAT
CREATE TABLE CHITIETPHIEUXUAT
(
	MAPX INT FOREIGN KEY(MAPX) REFERENCES PHIEUXUAT,
	MASP CHAR(5) FOREIGN KEY(MASP) REFERENCES SANPHAM,
	SOLUONG TINYINT
)
DROP TABLE CHITIETPHIEUXUAT

--CÂU 1
CREATE VIEW CAU1
AS
(
SELECT S.MASP,TENSP,SUM(SOLUONG) AS[TỔNG SỐ LƯỢNG ]
FROM SANPHAM S,CHITIETPHIEUXUAT C,PHIEUXUAT
WHERE S.MASP=C.MASP AND C.MAPX=PHIEUXUAT.MAPX AND YEAR(NGAYLAP)=2010
GROUP BY  S.MASP,TENSP 
)
GO
--CÂU 2
CREATE VIEW CAU2
AS
(
	SELECT DISTINCT SANPHAM.MASP,TENSP,TENLOAI
	FROM SANPHAM,PHIEUXUAT,LOAI,CHITIETPHIEUXUAT,NHANVIEN
	WHERE LOAI.MALOAI=SANPHAM.MALOAI AND SANPHAM.MASP=CHITIETPHIEUXUAT.MASP AND PHIEUXUAT.MAPX=CHITIETPHIEUXUAT.MAPX AND NHANVIEN.MANV=PHIEUXUAT.MANV AND (DAY(NGAYLAP)BETWEEN 1 AND 30) AND (MONTH(NGAYLAP)BETWEEN 1 AND 6) AND YEAR(NGAYLAP)=2010
)
-- CÂU 3
CREATE VIEW CAU3
AS
(
SELECT  LOAI.MALOAI,TENLOAI, SUM(SOLUONG) AS[SỐ LƯỢNG SP]
FROM LOAI,CHITIETPHIEUXUAT,PHIEUXUAT,SANPHAM
WHERE PHIEUXUAT.MAPX=CHITIETPHIEUXUAT.MAPX AND SANPHAM.MASP=CHITIETPHIEUXUAT.MASP AND SANPHAM.MALOAI=LOAI.MALOAI
GROUP BY  LOAI.MALOAI,TENLOAI
)
SELECT*FROM CAU3
DROP VIEW CAU3
-- CÂU 4
SET DATEFORMAT DMY
SELECT  COUNT(C.MAPX) AS[SỐ LƯỢNG PHIẾU XUẤT TRONG THÁNG 6]
FROM CHITIETPHIEUXUAT C,PHIEUXUAT,SANPHAM
WHERE C.MAPX=PHIEUXUAT.MAPX AND SANPHAM.MASP=C.MASP AND MONTH(NGAYLAP)=6 AND YEAR(NGAYLAP)=2010
ORDER BY [SỐ LƯỢNG PHIẾU XUẤT TRONG THÁNG 6]

-- CÂU 5
CREATE VIEW CAU5
AS
(
SELECT PHIEUXUAT.MAPX,C.MASP,SOLUONG,NGAYLAP,MANV
FROM PHIEUXUAT,CHITIETPHIEUXUAT C
WHERE  PHIEUXUAT.MAPX=C.MAPX AND MANV='NV01'
)
DROP VIEW CAU5
-- CÂU 6
SELECT *
FROM NHANVIEN
WHERE PHAI='1' AND (DATEDIFF(YEAR, NGAYSINH, GETDATE()) > 25 AND DATEDIFF(YEAR, NGAYSINH, GETDATE()) < 30)

-- CÂU 7
SELECT  PHIEUXUAT.MANV,HOTEN , COUNT(C.MAPX) AS[SỐ LƯỢNG PX CỦA TỪNG NV]
FROM NHANVIEN,CHITIETPHIEUXUAT C,PHIEUXUAT
WHERE C.MAPX=PHIEUXUAT.MAPX AND NHANVIEN.MANV=PHIEUXUAT.MANV
GROUP BY PHIEUXUAT.MANV,HOTEN
-- CÂU 8
SELECT  TENSP ,C.MASP, SUM(SOLUONG) AS[SỐ LƯỢNG SẢN PHẨM ĐÃ XUẤT]
FROM SANPHAM,CHITIETPHIEUXUAT C
WHERE SANPHAM.MASP=C.MASP
GROUP BY TENSP ,C.MASP
-- CÂU 9
SELECT TOP 1 PHIEUXUAT.MANV,HOTEN , COUNT(C.MAPX) AS[SỐ LƯỢNG PX CỦA NV]
FROM NHANVIEN,CHITIETPHIEUXUAT C,PHIEUXUAT
WHERE C.MAPX=PHIEUXUAT.MAPX AND NHANVIEN.MANV=PHIEUXUAT.MANV
GROUP BY PHIEUXUAT.MANV,HOTEN

-- CÂU 10
SELECT TOP 1 TENSP , SUM(SOLUONG) AS[SỐ LƯỢNG SẢN PHẨM XUẤT NHÌU NHẤT 2010]
FROM SANPHAM,CHITIETPHIEUXUAT C,PHIEUXUAT
WHERE SANPHAM.MASP=C.MASP AND PHIEUXUAT.MAPX=C.MAPX AND YEAR(NGAYLAP)=2010
GROUP BY TENSP ,C.MASP

--FUNCTION
--CÂU 1
CREATE FUNCTION C1(@TENSP NVARCHAR(50),@NAM INT)
RETURNS INT
AS
	BEGIN
	DECLARE @SOLUONG INT;
	SELECT @SOLUONG=SUM(SOLUONG)
	FROM SANPHAM,CHITIETPHIEUXUAT C,PHIEUXUAT
	WHERE C.MAPX=PHIEUXUAT.MAPX AND SANPHAM.MASP=C.MASP AND SANPHAM.TENSP=@TENSP AND YEAR(NGAYLAP)=@NAM
	RETURN @SOLUONG;
	END
GO
DROP FUNCTION C1
SELECT dbo.C1(N'Xi măng',2010)
--CÂU 2
CREATE FUNCTION C2(@MANV VARCHAR(5))
RETURNS INT
AS
	BEGIN
	DECLARE @TONG INT;
	SELECT @TONG= COUNT(C.MAPX) 
	FROM PHIEUXUAT,CHITIETPHIEUXUAT C
	WHERE C.MAPX=PHIEUXUAT.MAPX AND MANV=@MANV
	RETURN @TONG;
END
GO
DROP FUNCTION C2
SELECT dbo.C2('NV01')

-- CÂU 3
CREATE FUNCTION C3(@NAM INT)
RETURNS TABLE
AS
	
		RETURN
		(
		SELECT DISTINCT  SANPHAM.TENSP,SANPHAM.MASP
		FROM SANPHAM,PHIEUXUAT,CHITIETPHIEUXUAT C
		WHERE SANPHAM.MASP=C.MASP AND PHIEUXUAT.MAPX=C.MAPX AND YEAR(NGAYLAP)=@NAM
		)
	
GO
DROP FUNCTION C3

SELECT  * FROM C3 (2010)

-- CÂU 4
CREATE FUNCTION Cau4(@manv CHAR(5))
 RETURNS @ds TABLE(
    MAPX CHAR(5),
	MASP CHAR(5),
	SL INT
)
AS
	BEGIN
      IF(@manv IS NULL)
	  INSERT INTO  @ds SELECT * FROM CHITIETPHIEUXUAT
	  ELSE
	    INSERT INTO  @ds SELECT CHITIETPHIEUXUAT.MAPX,CHITIETPHIEUXUAT.MASP,CHITIETPHIEUXUAT.SOLUONG
		FROM CHITIETPHIEUXUAT join PHIEUXUAT ON CHITIETPHIEUXUAT.MAPX=PHIEUXUAT.MAPX
		WHERE PHIEUXUAT.MANV=@manv
		RETURN
		END
	SELECT * FROM Cau4 ('NV01')

-- CÂU 5
CREATE FUNCTION CC(@MAPX INT)
RETURNS NVARCHAR(50)
AS
		BEGIN
		DECLARE @TEN NVARCHAR(50);
			SELECT @TEN=NHANVIEN.HOTEN
			FROM NHANVIEN,PHIEUXUAT
			WHERE NHANVIEN.MANV=PHIEUXUAT.MANV AND MAPX=@MAPX
			RETURN @TEN;
		END

DROP FUNCTION C
SELECT dbo.CC(2)
select *
from PHIEUXUAT,NHANVIEN
where PHIEUXUAT.MANV=NHANVIEN.MANV
--CÂU 6
CREATE FUNCTION C6(@T1 INT,@T2 INT)
RETURNS NVARCHAR
AS
	BEGIN
		RETURN
			(
				SELECT P.MAPX
				FROM PHIEUXUAT P,CHITIETPHIEUXUAT C
				WHERE P.MAPX=C.MAPX AND (DATEDIFF(DAY, NGAYLAP, GETDATE()) >= @T1 AND DATEDIFF(DAY, NGAYLAP, GETDATE()) <= @T2)
			)
	END
GO
DROP FUNCTION C6
SELECT dbo.C6(1,3)

-- CÂU 7
CREATE FUNCTION C7(@MAPX INT)
RETURNS DATE
AS
	BEGIN
		DECLARE @NAM DATE;
		SELECT @NAM =PHIEUXUAT.NGAYLAP
		FROM PHIEUXUAT,CHITIETPHIEUXUAT C
		WHERE C.MAPX=PHIEUXUAT.MAPX AND PHIEUXUAT.MAPX=@MAPX
		RETURN @NAM;
	END
GO
DROP FUNCTION C7
PRINT 'NGAY LAP:' +CONVERT(VARCHAR(10),dbo.C7('4'))
-- PROCDURE
--CÂU 1
CREATE PROC P1(@TEN NVARCHAR(50))
AS
(
	SELECT SOLUONG=dbo.C1(@TEN,2010)
)
EXEC P1 N'Xi măng'
DROP PROC P1
--CÂU 2
CREATE PROC P2(@TENSP NVARCHAR(50))
AS

	IF NOT EXISTS (SELECT * FROM SANPHAM WHERE SANPHAM.TENSP = @TENSP)
		SELECT @TENSP=0
	ELSE
		SELECT SUM(SOLUONG)
		FROM CHITIETPHIEUXUAT C,SANPHAM,PHIEUXUAT
		WHERE SANPHAM.MASP=C.MASP AND C.MAPX=PHIEUXUAT.MAPX
		AND YEAR(NGAYLAP)=2010 AND MONTH(NGAYLAP) BETWEEN 4 AND 6
		AND SANPHAM.TENSP=@TENSP
DROP PROC P2
EXEC  P2 N'Xi măng'
-- CÂU 3
CREATE PROC P3(@TENSP NVARCHAR(50))
AS
		BEGIN
		DECLARE @SL INT;
		SELECT @SL=dbo.P2(@TENSP,2010)
		END
		DROP PROC P3
EXEC dbo.P3 N'Xi măng'

--CÂU 4
CREATE PROC C4(@MALOAI CHAR(5),@TENLOAI NVARCHAR(50))
AS
	INSERT INTO LOAI VALUES(@MALOAI,@TENLOAI)

EXEC dbo.C4 '4',N'Hàng công nghệ'
-- CÂU 5
CREATE PROC C5(@MANV VARCHAR(5))
AS
	
	DELETE 
	FROM NHANVIEN
	WHERE  MANV=@MANV
	
DROP PROC C5
EXEC dbo.C5 'NV02'

--TRIGGER
1.STORE PROCEDURE
2.CHỨC NĂNG: ĐẢM BẢO CÁC RNAFG BUỘC TOÀN VẸN(CONSTRAINT) -- MIỀN GIÁ TRỊ
3.TỰ ĐỘNG THỰC THI KHI CAN THIỆP VÀO DỮ LIỆU
INSERT:INSERTED (HỆ THỐNG)
DELETE:DELETED 
UPDATE:DELETED AND INSERTED
4.KHÔNG CÓ THAM SỐ ,CHẠY TRÊN SERVER

-- CÂU 1
CREATE TRIGGER C211 ON CHITIETPHIEUXUAT
FOR INSERT ,UPDATE
AS 
	DECLARE @MAPX VARCHAR(5) 
	SELECT @MAPX=MAPX FROM INSERTED
	IF(SELECT COUNT(*) FROM CHITIETPHIEUXUAT CT ,INSERTED I WHERE CT.MAPX=I.MAPX AND I.MAPX=@MAPX) >5

	BEGIN
		RAISERROR ('1 PHIEU XUAT CO TOI DA 5 CHI TIET',16,1) 
		ROLLBACK TRANSACTION
	END
GO
DROP TRIGGER C211
SELECT * FROM CHITIETPHIEUXUAT
SELECT * FROM SANPHAM
INSERT INTO CHITIETPHIEUXUAT VALUES('1','4',5)
INSERT INTO CHITIETPHIEUXUAT VALUES('1','5',5)
INSERT INTO CHITIETPHIEUXUAT VALUES('1','6',5)
-- CÂU 2
--cau 2:
create trigger C2_trigger on PHIEUXUAT
for insert ,update
as
    declare  @count int,@ngay date
	select @ngay= (select i.NGAYLAP from inserted i join PHIEUXUAT p on i.MAPX=p.MAPX)
	set @count=(select count(*) from PHIEUXUAT where NGAYLAP =@ngay
	   GROUP By PHIEUXUAT.MANV)
	if(@count >=11)
	begin 
	print('Lap Toi Da 10 Phieu Xuat Trong Mot Ngay')
	rollback tran
	end
	drop trigger C2_trigger
	insert into PHIEUXUAT(NGAYLAP,MANV) values ('12/03/2010','NV01')
--cau3:
create trigger C3_trigger on CHITIETPHIEUXUAT
for insert,update
as
    declare @mapx int
	select @mapx =(select MAPX from inserted)
	if not exists (select * from PHIEUXUAT where MAPX=@mapx)
	begin
	   print('Khong Ton Tai Ma Phieu Xuat')
	   rollback tran
	   end
	   else
	   begin
	     print('Them CTPX Thanh Cong')
		 commit tran
		 end

insert into CHITIETPHIEUXUAT values (100,'6',15)